### ISSUE TITLE
自動テスト

### ISSUE THREAD

**Issue by eggplants** [sora32127/healthy-person-emulator-dotorg#11]
## 概要

自動テストがあると、文法エラーやリンティングルールを無視したコードがコミットされることを防げます。

また、playwrightによるE2Eテストも用意されているので、これも自動で回せると嬉しいです。

GitHub Actionsのランナーは公開リポジトリだとどれだけ回しても[無料](https://docs.github.com/ja/billing/managing-billing-for-github-actions/about-billing-for-github-actions#github-actions-%E3%81%AE%E8%AA%B2%E9%87%91%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6:~:text=GitHub%20Actions%20%E3%81%AE%E4%BD%BF%E7%94%A8%E3%81%AF%E3%80%81%E3%83%91%E3%83%96%E3%83%AA%E3%83%83%E3%82%AF%20%E3%83%AA%E3%83%9D%E3%82%B8%E3%83%88%E3%83%AA%E3%81%AE%E6%A8%99%E6%BA%96%E3%81%AE%20GitHub%20%E3%83%9B%E3%82%B9%E3%83%86%E3%83%83%E3%83%89%20%E3%83%A9%E3%83%B3%E3%83%8A%E3%83%BC%E3%81%A8%E3%82%BB%E3%83%AB%E3%83%95%E3%83%9B%E3%82%B9%E3%83%86%E3%83%83%E3%83%89%20%E3%83%A9%E3%83%B3%E3%83%8A%E3%83%BC%E3%81%AE%E5%A0%B4%E5%90%88%E3%81%AF%E7%84%A1%E6%96%99%E3%81%A7%E3%81%99%E3%80%82)なので利用してテストできると嬉しいです。

## 備考

現在、ESLint のルールはありますが、フォーマッターは導入されていないようなので、Prettierなどを導入するといいかもしれません。

**Comment by sora32127** [comment]
@eggplants 
ご提案ありがとうございます。
今回は文法的なテストは行わず、PlaywrightによるE2Eテストのみを行おうと思います（現状では文法エラーが多すぎるため）
