### ISSUE TITLE
検索キーワードがエスケープされていない

### ISSUE THREAD

**Issue by eggplants** [sora32127/healthy-person-emulator-dotorg#126]
## 概要

[記事検索](https://healthy-person-emulator.org/search)にて、 `%` で検索すると全ての記事がヒットします。

`%`: https://healthy-person-emulator.org/search?p=1&orderby=timeDesc&q=%25

また `'` / `'''` などで検索すると500エラーになります。

`'`: https://healthy-person-emulator.org/search?p=1&orderby=timeDesc&q=%27
`'''`: https://healthy-person-emulator.org/search?p=1&orderby=timeDesc&q=%27%27%27

## 原因

これはLIKE句に検索キーワードを埋め込む際にエスケープしていないことで発生しています。 

https://github.com/sora32127/healthy-person-emulator-dotorg/blob/7726ff900258628e3c024a9667dbcebde26fae3d/app/modules/search.server.ts#L162
https://github.com/sora32127/healthy-person-emulator-dotorg/blob/7726ff900258628e3c024a9667dbcebde26fae3d/app/modules/search.server.ts#L486

## 対応案

Activerecord の [`sanitize_sql_like` メソッド](https://api.rubyonrails.org/v7.1/classes/ActiveRecord/Sanitization/ClassMethods.html#method-i-sanitize_sql_like)のようなものが Prisma にあるかわかりませんが、何らかのエスケープ処理が必要だと思います。

**Comment by sora32127** [comment]
@eggplants 
eggplantsさん、こちら報告ありがとうございました！この手の事象は自分では気づきづらいので、報告とても助かりました。

発生していた不具合に対処し、報告されたエラーが起こらないことを確認しました。エラーが発生していた原因はPRの方に記載してあります。

Issueはクローズとします。これからもよろしくお願いします。
